services:
  scraper:
    image: ${PROJECT_NAME}_scraper:${VERSION}
    container_name: scraper_service
    restart: no
    environment:
      - RUST_LOG=info
      - DB_PATH=/usr/src/app/db/reddit_scraper.db
      - DOCKER_ENV=1 
    volumes:
      - reddit_scraper_db:/usr/src/app/db/

  web:
    image: ${PROJECT_NAME}_web:${VERSION}
    container_name: web_service
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - RUST_LOG=info
      - DB_PATH=/usr/src/app/db/reddit_scraper.db
    volumes:
      - reddit_scraper_db:/usr/src/app/db/

  web-frontend:
    build: ./services/web-frontend
    container_name: frontend_service
    ports:
      - "3100:80"
    depends_on:
      - web

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - web
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    restart: unless-stopped

volumes:
  reddit_scraper_db:
  prometheus_data:
