services:
  scraper:
    image: ${PROJECT_NAME}_scraper:${VERSION}
    container_name: scraper_service
    restart: no
    environment:
      - RUST_LOG=info
      - DB_PATH=/usr/src/app/db/reddit_scraper.db
      - DOCKER_ENV=1 
      - RABBITMQ_URL=amqp://testuser:testpassword@rabbitmq:5672/test-vhost
    volumes:
      - reddit_scraper_db:/usr/src/app/db/
    depends_on:
      - rabbitmq

  worker:
    image: ${PROJECT_NAME}_worker:${VERSION}
    container_name: worker_service
    restart: unless-stopped
    environment:
      - RUST_LOG=info
      - DB_PATH=/usr/src/app/db/reddit_scraper.db
      - DOCKER_ENV=1 
      - RABBITMQ_URL=amqp://testuser:testpassword@rabbitmq:5672/test-vhost
    volumes:
      - reddit_scraper_db:/usr/src/app/db/
    depends_on:
      - rabbitmq

  web:
    image: ${PROJECT_NAME}_web:${VERSION}
    container_name: web_service
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - RUST_LOG=info
      - DB_PATH=/usr/src/app/db/reddit_scraper.db
      - RABBITMQ_URL=amqp://rabbitmq:5672
    volumes:
      - reddit_scraper_db:/usr/src/app/db/
    depends_on:
      - rabbitmq

  web-frontend:
    build: ./services/web-frontend
    container_name: frontend_service
    ports:
      - "3100:80"
    depends_on:
      - web

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - web
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    restart: unless-stopped

  rabbitmq:
    build:
      context: ./services/rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

volumes:
  reddit_scraper_db:
  prometheus_data:
