[package]
name = "databases"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = "0.32.1"
thiserror = "1.0.63"

[lib]
name = "databases"
path = "src/lib.rs"

[dev-dependencies]
tempfile = "3.12.0"
