[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
analyzer = { path = "../analyzer" }
models = { path = "../../models" }
rocket = "0.5.0-rc.2"
rocket_cors = "0.6.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
