[package]
name = "analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rusqlite = "0.32.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
models = { path = "../../models" }
