[package]
name = "analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rusqlite = "0.32.1"
models = { path = "../../models" }

[lib]
name = "analyzer"
path = "src/lib.rs"

[[bin]]
name = "analyzer"
path = "src/main.rs"
